services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - AWS_S3_BUCKET_NAME=${AWS_S3_BUCKET_NAME}
        - AWS_REGION=${AWS_REGION}
    working_dir: /app
    command: npm run dev
    entrypoint: ./entrypoint.sh
    volumes:
      - ~/.aws:/root/.aws:ro  # Mount host AWS credentials (read-only)
    ports:
      - "3000:3000"
      - "5555:5555" # Prisma Studio, optional
    env_file:
      - .env
    environment:
      NODE_OPTIONS: "--max-old-space-size=4096"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - koala-network

  db:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: prisma
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432" # To access the DB externally via pgAdmin and other tools
    networks:
      - koala-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U prisma"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:
    name: koala-db-data

networks:
  koala-network:
    name: koala-network
    driver: bridge

